/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busmansystem;

/**
 *
 * @author Elcid Chawa
 */

import javax.swing.ImageIcon;
import javax.swing.Icon;
import java.sql.*;
import java.util.Date;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.awt.print.*;
import java.util.ArrayList;
import java.util.List;
import java.awt.GridBagConstraints;
import java.time.LocalDate;
import javax.swing.*;

public class BusManPanel extends javax.swing.JPanel {
   
    List<City> cities = new ArrayList<City>();
    List<Buses> buses = new ArrayList<Buses>();
    Client clients = new Client();
    QueryDatabase query = new QueryDatabase();
    
    GridBagConstraints busGridPanelConstraints = new GridBagConstraints();
    
    Icon green; 
    Icon red; 
    Boolean check;
    
    
    /**
     * Creates new form BusManPanel
     */
    public BusManPanel() {
        initComponents();
        green = new ImageIcon( getClass().getResource("/components/images/green.jpg") );
        red = new ImageIcon( getClass().getResource("/components/images/red.jpg") );
        check = true;
        inititialize_all();
    }
    
    private void inititialize_all() {
       cities = query.getCities();
        
        for (City c : cities){
        this.tFromComboBox.addItem(c.getCity());
        this.rFromComboBox.addItem(c.getCity());
        }
        
        for (City c : cities){
        this.tToComboBox.addItem(c.getCity());
        this.rToComboBox.addItem(c.getCity());
        }
        
        buses = query.getBuses();
        
        for(Buses b : buses){
            this.tBusComboBox.addItem(b.getBusID());
            this.reportComboBox.addItem(b.getBusID());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jTextField7 = new javax.swing.JTextField();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("bussystem?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        bustableQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT b FROM Bustable b");
        bustableList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : bustableQuery.getResultList();
        systemPanel = new javax.swing.JTabbedPane();
        clientBookinPanel = new javax.swing.JPanel();
        clientPanel = new javax.swing.JPanel();
        fName = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        idCard = new javax.swing.JLabel();
        fnameTextField = new javax.swing.JTextField();
        lnameTextField = new javax.swing.JTextField();
        idCardTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        travelPanel = new javax.swing.JPanel();
        travelLabel = new javax.swing.JLabel();
        from = new javax.swing.JLabel();
        to = new javax.swing.JLabel();
        tFromComboBox = new javax.swing.JComboBox<>();
        tToComboBox = new javax.swing.JComboBox<>();
        depatureDate = new javax.swing.JLabel();
        tSelectDepatureDate = new org.jdesktop.swingx.JXDatePicker();
        busPanel = new javax.swing.JPanel();
        busIDLabel = new javax.swing.JLabel();
        seatCapLabel = new javax.swing.JLabel();
        seatsLeftLabel = new javax.swing.JLabel();
        seatsLeftTextField = new javax.swing.JTextField();
        busGridPanel = new javax.swing.JPanel();
        seatGridLabel = new javax.swing.JLabel();
        tBusComboBox = new javax.swing.JComboBox<>();
        planTripButton = new javax.swing.JButton();
        resetFieldsButton = new javax.swing.JButton();
        adminPanel = new javax.swing.JPanel();
        jXLoginPane1 = new org.jdesktop.swingx.JXLoginPane();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        reportgenPanel = new javax.swing.JPanel();
        reportPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rDatePicker = new org.jdesktop.swingx.JXDatePicker();
        rToComboBox = new javax.swing.JComboBox<>();
        rFromComboBox = new javax.swing.JComboBox<>();
        reportComboBox = new javax.swing.JComboBox<>();
        reportBusType = new javax.swing.JTextField();
        generateListButton = new javax.swing.JButton();
        listPanel = new javax.swing.JScrollPane();
        list = new javax.swing.JTable();
        print_list = new javax.swing.JButton();

        jTextField7.setText("jTextField7");

        setBackground(new java.awt.Color(97, 212, 195));

        systemPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        systemPanel.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        systemPanel.setToolTipText("system panel");
        systemPanel.setPreferredSize(new java.awt.Dimension(850, 750));
        systemPanel.setRequestFocusEnabled(false);

        clientBookinPanel.setBackground(new java.awt.Color(97, 212, 195));
        clientBookinPanel.setPreferredSize(new java.awt.Dimension(850, 700));

        clientPanel.setBackground(new java.awt.Color(36, 47, 65));
        clientPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fName.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        fName.setForeground(new java.awt.Color(255, 255, 255));
        fName.setText("FIRST NAME:");

        lName.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lName.setForeground(new java.awt.Color(255, 255, 255));
        lName.setText("LAST NAME");

        idCard.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        idCard.setForeground(new java.awt.Color(255, 255, 255));
        idCard.setText("ID Card No:");

        fnameTextField.setBackground(new java.awt.Color(36, 47, 65));
        fnameTextField.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        fnameTextField.setForeground(new java.awt.Color(255, 255, 255));
        fnameTextField.setBorder(null);

        lnameTextField.setBackground(new java.awt.Color(36, 47, 65));
        lnameTextField.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lnameTextField.setForeground(new java.awt.Color(255, 255, 255));
        lnameTextField.setBorder(null);
        lnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameTextFieldActionPerformed(evt);
            }
        });

        idCardTextField.setBackground(new java.awt.Color(36, 47, 65));
        idCardTextField.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        idCardTextField.setForeground(new java.awt.Color(255, 255, 255));
        idCardTextField.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Client Information");

        javax.swing.GroupLayout clientPanelLayout = new javax.swing.GroupLayout(clientPanel);
        clientPanel.setLayout(clientPanelLayout);
        clientPanelLayout.setHorizontalGroup(
            clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(lnameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fnameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(clientPanelLayout.createSequentialGroup()
                        .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idCard, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lName))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idCardTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        clientPanelLayout.setVerticalGroup(
            clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idCard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idCardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        travelPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        travelLabel.setText("Travel Plan");

        from.setText("From");

        to.setText("To");

        tFromComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select City ..." }));
        tFromComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFromComboBoxActionPerformed(evt);
            }
        });

        tToComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select City ..." }));

        depatureDate.setText("Depature Date");

        tSelectDepatureDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSelectDepatureDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout travelPanelLayout = new javax.swing.GroupLayout(travelPanel);
        travelPanel.setLayout(travelPanelLayout);
        travelPanelLayout.setHorizontalGroup(
            travelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(travelPanelLayout.createSequentialGroup()
                .addGroup(travelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(travelPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(travelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(depatureDate)
                            .addGroup(travelPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(travelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(to)
                                    .addComponent(from))))
                        .addGap(53, 53, 53)
                        .addGroup(travelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tSelectDepatureDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tFromComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tToComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(travelPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(travelLabel)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        travelPanelLayout.setVerticalGroup(
            travelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(travelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(travelLabel)
                .addGap(39, 39, 39)
                .addGroup(travelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(from))
                .addGap(39, 39, 39)
                .addGroup(travelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tToComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(to))
                .addGap(58, 58, 58)
                .addGroup(travelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depatureDate)
                    .addComponent(tSelectDepatureDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        busPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        busIDLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        busIDLabel.setText("Bus ID");

        seatCapLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        seatCapLabel.setText("Seating Capacity");

        seatsLeftLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        seatsLeftLabel.setText("Number of seats left");

        seatsLeftTextField.setEditable(false);

        busGridPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        busGridPanel.setVerifyInputWhenFocusTarget(false);
        java.awt.GridBagLayout busGridPanelLayout = new java.awt.GridBagLayout();
        busGridPanelLayout.columnWidths = new int[] {6};
        busGridPanelLayout.rowHeights = new int[] {5};
        busGridPanelLayout.columnWeights = new double[] {1.0};
        busGridPanelLayout.rowWeights = new double[] {1.0};
        busGridPanel.setLayout(busGridPanelLayout);

        seatGridLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        seatGridLabel.setText("Bus Seating Grid");

        tBusComboBox.setSelectedItem(null);
        tBusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBusComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout busPanelLayout = new javax.swing.GroupLayout(busPanel);
        busPanel.setLayout(busPanelLayout);
        busPanelLayout.setHorizontalGroup(
            busPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(busPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(busIDLabel)
                    .addComponent(seatCapLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, busPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(seatGridLabel)
                        .addComponent(seatsLeftLabel)))
                .addGap(29, 29, 29)
                .addGroup(busPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tBusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatsLeftTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, busPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(busGridPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        busPanelLayout.setVerticalGroup(
            busPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(busPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busIDLabel)
                    .addComponent(tBusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(seatCapLabel)
                .addGap(45, 45, 45)
                .addGroup(busPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatsLeftLabel)
                    .addComponent(seatsLeftTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(seatGridLabel)
                .addGap(31, 31, 31)
                .addComponent(busGridPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        busGridPanel.getAccessibleContext().setAccessibleName("");
        busGridPanel.getAccessibleContext().setAccessibleDescription("");

        planTripButton.setText("Plan");
        planTripButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planTripButtonActionPerformed(evt);
            }
        });

        resetFieldsButton.setText("Reset");
        resetFieldsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetFieldsButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout clientBookinPanelLayout = new javax.swing.GroupLayout(clientBookinPanel);
        clientBookinPanel.setLayout(clientBookinPanelLayout);
        clientBookinPanelLayout.setHorizontalGroup(
            clientBookinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientBookinPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(planTripButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(resetFieldsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(clientBookinPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientBookinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(travelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(busPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        clientBookinPanelLayout.setVerticalGroup(
            clientBookinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientBookinPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(clientBookinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(clientBookinPanelLayout.createSequentialGroup()
                        .addComponent(clientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(travelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(busPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientBookinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planTripButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetFieldsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        systemPanel.addTab("Client Booking", clientBookinPanel);

        jXLoginPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jButton4.setText("Login");

        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jXLoginPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addContainerGap(406, Short.MAX_VALUE))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jXLoginPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(403, Short.MAX_VALUE))
        );

        systemPanel.addTab("Admin Panel", adminPanel);

        reportgenPanel.setBackground(new java.awt.Color(97, 212, 195));

        reportPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setText("BusID");

        jLabel2.setText("Bus Name / Type");

        jLabel8.setText("From");

        jLabel9.setText("To");

        jLabel12.setText("Date");

        rToComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select City" }));

        rFromComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select City ..." }));

        reportComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Bus..." }));

        reportBusType.setText("jTextField1");

        generateListButton.setText("Generate Bording List");

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reportBusType, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1))
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(reportPanelLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rFromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(reportComboBox, 0, 144, Short.MAX_VALUE)
                                        .addComponent(rDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(rToComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(reportPanelLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(generateListButton)))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(reportComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(rDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rFromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rToComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(34, 34, 34)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(reportBusType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(generateListButton)
                .addGap(87, 87, 87))
        );

        listPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "Boarding row List", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Aquatico", 1, 18))); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, bustableQuery, org.jdesktop.beansbinding.ObjectProperty.create(), list, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding.bind();
        listPanel.setViewportView(list);

        print_list.setText("Print");
        print_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_listActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reportgenPanelLayout = new javax.swing.GroupLayout(reportgenPanel);
        reportgenPanel.setLayout(reportgenPanelLayout);
        reportgenPanelLayout.setHorizontalGroup(
            reportgenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportgenPanelLayout.createSequentialGroup()
                .addGroup(reportgenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportgenPanelLayout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(print_list, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(reportgenPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(reportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(listPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        reportgenPanelLayout.setVerticalGroup(
            reportgenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportgenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportgenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(print_list, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        systemPanel.addTab("Report", reportgenPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(systemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(systemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        systemPanel.getAccessibleContext().setAccessibleName("Client Reservation");

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void lnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameTextFieldActionPerformed

    private void tSelectDepatureDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSelectDepatureDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSelectDepatureDateActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tFromComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFromComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFromComboBoxActionPerformed

    private void resetFieldsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetFieldsButtonMouseClicked
        // clear all fields for entries
        fnameTextField.setText(null);
        lnameTextField.setText(null);
        idCardTextField.setText(null);
        tBusComboBox.setSelectedItem("Select Bus...");
        tFromComboBox.setSelectedItem("Select City ...");
        tToComboBox.setSelectedItem("Select City ...");
        
    }//GEN-LAST:event_resetFieldsButtonMouseClicked

    private void planTripButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planTripButtonActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        final String stringDate = dateFormat.format(tSelectDepatureDate.getDate());
        String fname = fnameTextField.getText();
        String lname = lnameTextField.getText();
        String id = idCardTextField.getText();
        String fromCity  = tFromComboBox.getSelectedItem().toString();
        String toCity =  tToComboBox.getSelectedItem().toString();
        String bus = tBusComboBox.getSelectedItem().toString();
         
        final java.sql.Date selectedDate = java.sql.Date.valueOf(stringDate); 
        
        System.out.println("Selected date: " + selectedDate.toString());
        
        clients = query.insertClient(id, fname, lname, 00);
        query.bookClient(id, buses.get(tBusComboBox.getSelectedIndex()).getBusID(), 
                8, cities.get(tToComboBox.getSelectedIndex()).getCityId(), selectedDate);
        JOptionPane.showMessageDialog(null, "Client Names: " + fname + " " 
                + lname + " \n Bus: " + bus + " \n Destination City: " + toCity + ".", 
                "Confirm Reservation", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_planTripButtonActionPerformed

    private void print_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_listActionPerformed
        
        MessageFormat header = new MessageFormat("Report Head");
        MessageFormat footer = new MessageFormat("Page number");
        try{
            list.print(JTable.PrintMode.NORMAL, header, footer);
        } catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %s %n", e, e.getMessage());
        }
    }//GEN-LAST:event_print_listActionPerformed

    private void tBusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBusComboBoxActionPerformed
        String selectedBus; int index, capacity;
        selectedBus = tBusComboBox.getSelectedItem().toString();
        index = tBusComboBox.getSelectedIndex();
        capacity = buses.get(index).getBusSeatCapacity();
        if (index !=0){
           JOptionPane.showMessageDialog(null, "You selected a bus "
                   + selectedBus + " with capacity = " 
                   + capacity + " seats.", "seats", JOptionPane.PLAIN_MESSAGE);
           
           
        }       
    }//GEN-LAST:event_tBusComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminPanel;
    private javax.swing.JPanel busGridPanel;
    private javax.swing.JLabel busIDLabel;
    private javax.swing.JPanel busPanel;
    private java.util.List<busmansystem.Bustable> bustableList;
    private javax.persistence.Query bustableQuery;
    private javax.swing.JPanel clientBookinPanel;
    private javax.swing.JPanel clientPanel;
    private javax.swing.JLabel depatureDate;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel fName;
    private javax.swing.JTextField fnameTextField;
    private javax.swing.JLabel from;
    private javax.swing.JButton generateListButton;
    private javax.swing.JLabel idCard;
    private javax.swing.JTextField idCardTextField;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField7;
    private org.jdesktop.swingx.JXLoginPane jXLoginPane1;
    private javax.swing.JLabel lName;
    private javax.swing.JTable list;
    private javax.swing.JScrollPane listPanel;
    private javax.swing.JTextField lnameTextField;
    private javax.swing.JButton planTripButton;
    private javax.swing.JButton print_list;
    private org.jdesktop.swingx.JXDatePicker rDatePicker;
    private javax.swing.JComboBox<String> rFromComboBox;
    private javax.swing.JComboBox<String> rToComboBox;
    private javax.swing.JTextField reportBusType;
    private javax.swing.JComboBox<String> reportComboBox;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JPanel reportgenPanel;
    private javax.swing.JButton resetFieldsButton;
    private javax.swing.JLabel seatCapLabel;
    private javax.swing.JLabel seatGridLabel;
    private javax.swing.JLabel seatsLeftLabel;
    private javax.swing.JTextField seatsLeftTextField;
    private javax.swing.JTabbedPane systemPanel;
    private javax.swing.JComboBox<String> tBusComboBox;
    private javax.swing.JComboBox<String> tFromComboBox;
    private org.jdesktop.swingx.JXDatePicker tSelectDepatureDate;
    private javax.swing.JComboBox<String> tToComboBox;
    private javax.swing.JLabel to;
    private javax.swing.JLabel travelLabel;
    private javax.swing.JPanel travelPanel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
